### ISSUE TITLE
The link for sdk v4.8 and v4.9 is expired

### ISSUE THREAD

**Issue by kbtxwer** [Hellikandra/ATAK-Dev-Docker#1]

**Comment by Hellikandra** [comment]
Hi, sorry for being long to answer..

Yes, it is due to the new version of ATAK SDK available on tak.gov.
I think I will just set a generic unzip name to copy the SDK you have local to the docker.

Thanks for the report.

**Comment by Hellikandra** [comment]
Links modified to be more generic to TAK.gov,
Inside each version, the zip file is renamed to be more generic.
